# Use postgres/example user/password credentials
# restart: always
version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - /home/alvaroico/GitHub/RocketseatLaunchBase/CadastrandoUsuarios/modulo7.2/PostgreSQL:/var/lib/postgresql/data 
    

  adminer:
    image: adminer
    ports:
      - 8080:8080