# Use postgres/example user/password credentials
# restart: always
# docker-compose up -d
version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - D:\Users\alvaroico\GitHub\RocketseatLaunchBase\CadastrandoUsuarios\modulo7.2\PostgreSql\data:/var/lib/postgresql/data 
    

  adminer:
    image: adminer
    ports:
      - 8080:8080